#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
LAB_DIR="$SCRIPT_DIR/lab-repo"
FORCE=false

usage() {
  cat <<USAGE
Usage: $0 [--force]

Create a self-contained Git practice repository under:
  $LAB_DIR

Options:
  --force   Remove an existing lab repository first.
USAGE
}

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=true ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; usage >&2; exit 2 ;;
  esac
done

command -v git >/dev/null 2>&1 || { echo "git is required" >&2; exit 1; }

if [[ -e "$LAB_DIR" ]]; then
  if [[ "$FORCE" != true ]]; then
    echo "Lab already exists: $LAB_DIR" >&2
    echo "Use --force to recreate it." >&2
    exit 1
  fi
  rm -rf -- "$LAB_DIR"
fi

mkdir -p "$LAB_DIR/app" "$LAB_DIR/logs"
cd "$LAB_DIR"

git init -q -b main
git config user.name "DevOps Lab"
git config user.email "devops-lab@example.invalid"

cat > README.md <<'LABEOF'
# Git Team Workflow Lab

This repository is generated by Project 06.
LABEOF
cat > app/config.txt <<'LABEOF'
environment=development
logging=basic
LABEOF
cat > .gitignore <<'LABEOF'
*.log
.DS_Store
LABEOF

git add README.md app/config.txt .gitignore
git commit -q -m "chore: initialize application"

git switch -q -c feature/observability
printf 'environment=development\nlogging=structured\nmetrics=enabled\n' > app/config.txt
git add app/config.txt
git commit -q -m "feat: add observability settings"

git switch -q main
git switch -q -c feature/conflict
printf 'environment=staging\nlogging=basic\n' > app/config.txt
git add app/config.txt
git commit -q -m "feat: stage configuration"

git switch -q main

echo "Lab created at: $LAB_DIR"
echo "Branches:"
git branch --list
echo "Recent history:"
git log --oneline --graph --decorate --all -n 8
